kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-guard
  labels:
    branch: tilt
    commit_id: tilt
spec:
  selector:
    matchLabels:
      app: edge-guard
  template:
    spec:
      containers:
        - name: edge-guard
          image: amaas-eos-drm2.cec.lab.emc.com:5074/edge-guard/TAG # The docker image location to deploy the pod from (pipeline will update this automatically)
          resources:
            requests:
              cpu: 100m # How much CPU we are expecting the app container to require.
          ports:
            - containerPort: 8080
          startupProbe: # More on probes configuration: https://confluence.dell.com/x/pZMXDw
            initialDelaySeconds: 40
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/edge-guard/actuator/health/readiness
          readinessProbe: # Our readinessProbe configurations, more at: https://confluence.dell.com/x/pZMXDw
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/edge-guard/actuator/health/readiness
            timeoutSeconds: 2
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/edge-guard/actuator/health/liveness
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
