apiVersion: v1
kind: Service
metadata:
  name: edge-guard
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 5005
      protocol: TCP
      targetPort: 5005
      name: debug
