name: Azure Spring App Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure Spring Cloud
        uses: azure/spring-cloud-deploy@v1
        with:
          appName: 'edge-guard' # Replace with your app name
          resourceGroup: 'edge-guard' # Replace with your resource group
          location: 'East US' # Replace with your Azure region

        env:
          SPRING_CLOUD_CLIENT_ID: ${{ secrets.AZURE_SPRING_CLOUD_CLIENT_ID }}
          SPRING_CLOUD_CLIENT_SECRET: ${{ secrets.AZURE_SPRING_CLOUD_CLIENT_SECRET }}
          SPRING_CLOUD_TENANT_ID: ${{ secrets.AZURE_SPRING_CLOUD_TENANT_ID }}

